version: "3.3"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: Nginx
        ports:
            - "8080:80"
        volumes:
            - "./:/var/www/html/"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: Mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: laravel-vue
            # DB_USERNAME: user
            # DB_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_SERVICE_TAG: dev
            MYSQL_SERVICE_NAME: mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        links:
            - mysql:db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        depends_on:
            - mysql
        ports:
            - "8083:80"
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: DockerFile
        container_name: PHP
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www/html"
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: Composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laravel

    npm:
        image: node:13.7
        container_name: NPM
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["npm"]

    artisan:
        build:
            context: .
            dockerfile: DockerFile
        container_name: PHPArtisan
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - laravel
