version: '3'
networks:
  pr-network: 
   driver: bridge

services:
  nginx: 
    image: 'nginx:stable-alpine'
    container_name: 'nginx_${APP_NAME}'
    hostname: nginx
    restart: unless-stopped
    ports:
      - '82:80'
    volumes: 
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - pr-network
    
  mysql:
    image: 'mysql:5.7.22'
    container_name: 'mysql_${APP_NAME}'
    hostname: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=pratice
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=1234
    networks:
      - pr-network
    volumes:
      - ./db:/var/lib/mysql
  php:
    container_name: 'php_${APP_NAME}'
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: php
    ports:
      - '9002:9000'
    restart: unless-stopped
    networks: 
      - pr-network
    volumes:
      - './src:/var/www/html'
  composer:
    image: 'composer:latest'
    container_name: 'composer_${APP_NAME}'
    volumes:
      - './src:/var/www/html'
    networks:
      - pr-network
  npm:
    image: 'node:13.7'
    container_name: 'npm_${APP_NAME}'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    entrypoint: 
      - npm
  
    
 
  

    